title: Siti Nurrohmah # your name (or website title) here
logo: "/images/siti.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Being one of the current 5th semester students at the Indonesian University of Education, System Education and Information Technology Study Program.
  <br><br>
  I would like to further explore the capabilities and experience in the Information Technology (IT) field
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <a href="https://twitter.com/nurrohmahs901">View My twitter Profile</a>
  <a href="https://instagram.com/sitinrrhmh21">View My instagram Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
